YES_CHOICE          = 1
NO_CHOICE           = 0
EMPTY_FIELD_ELEMENT = 0
ROBOT_FIELD_ELEMENT = 1
DEFAULT_SIZE_X      = 5
DEFAULT_SIZE_Y      = 6

USER_COMMAND_MOVE   = 'MOVE'
USER_COMMAND_LEFT   = 'LEFT'
USER_COMMAND_RIGHT  = 'RIGHT'
USER_COMMAND_REPORT = 'REPORT'
USER_COMMAND_PLACE  = 'PLACE'

DIRECTION_NORTH     = 'NORTH'
DIRECTION_SOUTH     = 'SOUTH'
DIRECTION_EAST      = 'EAST'
DIRECTION_WEST      = 'WEST'

CONTROL_COMMAND_PLACE        = 0
PARAM_PLACE_COMMAND_POSITION = 1

X_PLACE_PARAMETER         = 0
Y_PLACE_PARAMETER         = 1
DIRECTION_PLACE_PARAMETER = 2

VALID_SPLIT_COMMAND_SIZE  = 2

VALID_PARAMS_PLACE_SIZE   = 3

TURN_DIRECTION_LEFT       = 'LEFT'
TURN_DIRECTION_RIGHT      = 'RIGHT'

CONTROL_COMMANDS_ARRAY    = %w[MOVE LEFT RIGHT REPORT PLACE]

FIRST_FIELD_ARRAY_ELEMENT = 0
